### ISSUE TITLE
ST3 crash on OSX

### ISSUE THREAD

**Issue by berkus** [pfultz2/ClangComplete#6]
complete_at 
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

Is there any recommendations how to debug such crashes?
I compiled ClangComplete on OSX with slight Makefile modifications, it is loaded but then immediately crashes plugin_host on first (or second) completion attempt.

**Comment by pfultz2** [comment]
Ok, there was changes merged into develop that support mac. Let me know if that works for you.

**Comment by berkus** [comment]
I've installed it and will run tests for a while.

**Comment by berkus** [comment]
Seems to work fine here! Cheers!
