### ISSUE TITLE
Mac?

### ISSUE THREAD

**Issue by hzsweers** [pfultz2/ClangComplete#7]
Is there a path you recommend for using this on mac? I can't get it to work with my version of LLVM (doesn't recognize what a `vector` is of all things)

**Comment by Alexthelionheart** [comment]
@johnofcamas 
@hzsweers 
I got it working on a mac 
I got it working by first installing Clang using llvm, you can get brew [here] (http://www.brew.sh) 
then run
`brew install llvm`
to install llvm with gcc 
and finally change you makefile to contain 
````
CXX=g++

CLANG_PREFIX=$(shell (cd /usr/local/include/clang-c/ && cd ../.. && pwd) 2> /dev/null || (cd /usr/lib/llvm-3.5/ && pwd) 2> /dev/null || (cd /usr/lib/llvm-3.4/ && pwd) 2> /dev/null || (cd /usr/lib/llvm-3.3/ && pwd) 2> /dev/null || (cd /usr/local/Cellar/llvm/3.5.1 && pwd) 2> /dev/null)
CLANG_FLAGS=-I$(CLANG_PREFIX)/include/
CLANG_LIBS=-L$(CLANG_PREFIX)/lib/ -Wl,-rpath $(CLANG_PREFIX)/lib -lclang

FLAGS=$(CLANG_FLAGS)
LIBS=$(CLANG_LIBS)

LIB_NAME=libcomplete
SRC=complete
$(warning $(CLANG_FLAGS))
all:
	$(CXX) -std=c++11 $(FLAGS) -DNDEBUG -Os -c -fPIC complete.cpp -o $(SRC).o
	$(CXX) -shared -Wl,-install_name,$(LIB_NAME).so -o $(LIB_NAME).so $(SRC).o $(LIBS)
debug:
	$(CXX) -std=gnu++0x $(FLAGS) -g -c -fPIC -DCLANG_COMPLETE_LOG $(SRC).cpp -o $(SRC).o
	$(CXX) -shared -Wl,-install_name,$(LIB_NAME).so -o $(LIB_NAME).so $(SRC).o $(LIBS)
log:
	$(CXX) -std=gnu++0x $(FLAGS) -Os -c -fPIC -DCLANG_COMPLETE_LOG $(SRC).cpp -o $(SRC).o
	$(CXX) -shared -Wl,-install_name,$(LIB_NAME).so -o $(LIB_NAME).so $(SRC).o $(LIBS)

````

**Comment by pfultz2** [comment]
Changes have been update to build and support mac. Let me know if there is anymore issues.

**Comment by pfultz2** [comment]
Also, for now, you will need to checkout the develop branch for the changes.

**Comment by johnofcamas** [comment]
Sorry,  I think I resolved this once before but I can’t remember how:

$ make
complete.cpp:11:10: fatal error: 'Python.h' file not found
#include <Python.h>


Thoughts?

**Comment by johnofcamas** [comment]
My bad (wrong/old makefile), this is getting much closer, not it fails at the following step:

Makefile:12: -I/usr/local/Cellar/llvm/3.5.1/include/
g++ -std=c++11 -I/usr/local/Cellar/llvm/3.5.1/include/ -DNDEBUG -Os -c -fPIC complete.cpp -o complete.o
g++ -shared -Wl,-install_name,libcomplete.so -o libcomplete.so complete.o -L/usr/local/Cellar/llvm/3.5.1/lib/ -Wl,-rpath=/usr/local/Cellar/llvm/3.5.1/lib -lclang
ld: unknown option: -rpath=/usr/local/Cellar/llvm/3.5.1/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1

**Comment by johnofcamas** [comment]
Fixed by removing the ‘=‘ from rpath
